version: 0.0.2

application:
  - url: ""
    key: ""

client:
  - url: ""
    key: ""

logs:
  strict_mode: false
  show_debug: false
  show_http_log: false
  show_ws_log: false
  log_http_requests: false
  error_out_dir: ""
