version: 0.0.2
application:
  url: ""
  key: ""
client:
  url: ""
  key: ""
logs:
  showDebug: false
  showHttp: false
  showWebsocket: false
  useColour: true
http:
  saveRequests: false
  sendFullBody: false
  retryRatelimit: false
core:
  ignoreWarnings: false
  stopAtSysError: false
  saveErrorLogs: true
