version: 0.0.2

application:
  url: ""
  key: ""

client:
  url: ""
  key: ""

logs:
  show_debug: false
  show_http_log: false
  show_ws_log: false
  log_http_requests: false
  ignore_warnings: false
  cache_metadata: true
  send_full_body: false
