version: 0.0.2

application:
  url: ""
  key: ""

client:
  url: ""
  key: ""

logs:
  show_debug: false
  show_http: false
  show_websocket: false
  use_colour: true

http:
  save_requests: true
  send_full_body: false
  retry_ratelimit: false

core:
  ignore_warnings: false
  stop_at_sys_error: false
  save_error_logs: true
